import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import pg from 'pg';const{Pool}=pg;const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),FILE=path.join(ROOT,'Studio','data','studio-4.6.json');const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;async function fr(){try{return JSON.parse(await fs.readFile(FILE,'utf8'))}catch{return{users:[],projects:[],builds:[]}}}async function fw(d){await fs.mkdir(path.dirname(FILE),{recursive:true});await fs.writeFile(FILE,JSON.stringify(d,null,2))}export const dbMode=()=>pool?'postgres':'json';export async function ensureStore(){if(pool){await pool.query(`CREATE TABLE IF NOT EXISTS users(user_id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS projects(project_id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,idea TEXT NOT NULL,version TEXT NOT NULL DEFAULT '4.6.0',status TEXT NOT NULL DEFAULT 'created',blueprint JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS builds(build_id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'queued',payload JSONB NOT NULL DEFAULT '{}'::jsonb,result JSONB,error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ);CREATE INDEX IF NOT EXISTS builds_queue_idx ON builds(status,created_at)`)}else await fw(await fr())}
export async function findUserByEmail(email){if(pool){const r=await pool.query('SELECT * FROM users WHERE lower(email)=lower($1)',[email]);return r.rows[0]||null}const d=await fr();return d.users.find(u=>u.email.toLowerCase()===email.toLowerCase())||null}
export async function findUser(id){if(pool){const r=await pool.query('SELECT user_id,email,name,created_at FROM users WHERE user_id=$1',[id]);return r.rows[0]||null}const d=await fr();const u=d.users.find(x=>x.userId===id);return u?{user_id:u.userId,email:u.email,name:u.name,created_at:u.createdAt}:null}
export async function createUser(u){if(pool){await pool.query('INSERT INTO users(user_id,email,name,password_hash) VALUES($1,$2,$3,$4)',[u.userId,u.email,u.name,u.passwordHash]);return findUser(u.userId)}const d=await fr();d.users.push(u);await fw(d);return{user_id:u.userId,email:u.email,name:u.name,created_at:u.createdAt,password_hash:u.passwordHash}}
export async function listProjects(uid){if(pool){const r=await pool.query('SELECT * FROM projects WHERE user_id=$1 ORDER BY updated_at DESC',[uid]);return r.rows.map(pgP)}const d=await fr();return d.projects.filter(p=>p.userId===uid).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}function pgP(p){return{projectId:p.project_id,userId:p.user_id,idea:p.idea,version:p.version,status:p.status,blueprint:p.blueprint,createdAt:p.created_at,updatedAt:p.updated_at}}
export async function getProject(id,uid){if(pool){const r=await pool.query('SELECT * FROM projects WHERE project_id=$1 AND user_id=$2',[id,uid]);return r.rows[0]?pgP(r.rows[0]):null}const d=await fr();return d.projects.find(p=>p.projectId===id&&p.userId===uid)||null}
export async function createProject(p){if(pool){await pool.query('INSERT INTO projects(project_id,user_id,idea,version,status) VALUES($1,$2,$3,$4,$5)',[p.projectId,p.userId,p.idea,p.version,p.status]);return getProject(p.projectId,p.userId)}const d=await fr();d.projects.push(p);await fw(d);return p}
export async function updateProject(p){if(pool){await pool.query('UPDATE projects SET idea=$1,version=$2,status=$3,blueprint=$4,updated_at=NOW() WHERE project_id=$5 AND user_id=$6',[p.idea,p.version,p.status,p.blueprint?JSON.stringify(p.blueprint):null,p.projectId,p.userId]);return getProject(p.projectId,p.userId)}const d=await fr();const i=d.projects.findIndex(x=>x.projectId===p.projectId&&x.userId===p.userId);if(i>=0)d.projects[i]=p;else d.projects.push(p);await fw(d);return p}
export async function enqueueBuild(b){if(pool){await pool.query('INSERT INTO builds(build_id,project_id,user_id,status,payload) VALUES($1,$2,$3,$4,$5)',[b.buildId,b.projectId,b.userId,'queued',JSON.stringify(b.payload)]);return b}const d=await fr();d.builds.push(b);await fw(d);return b}
export async function getBuild(id,uid){if(pool){const r=await pool.query('SELECT * FROM builds WHERE build_id=$1 AND user_id=$2',[id,uid]);return r.rows[0]?pgB(r.rows[0]):null}const d=await fr();return d.builds.find(b=>b.buildId===id&&b.userId===uid)||null}function pgB(b){return{buildId:b.build_id,projectId:b.project_id,userId:b.user_id,status:b.status,payload:b.payload,result:b.result,error:b.error,createdAt:b.created_at,startedAt:b.started_at,finishedAt:b.finished_at}}
export async function claimNextBuild(){if(pool){const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query("SELECT * FROM builds WHERE status='queued' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1");if(!r.rows[0]){await c.query('COMMIT');return null}const b=r.rows[0];await c.query("UPDATE builds SET status='running',started_at=NOW() WHERE build_id=$1",[b.build_id]);await c.query('COMMIT');return{...pgB(b),status:'running'}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}const d=await fr(),b=d.builds.find(x=>x.status==='queued');if(!b)return null;b.status='running';b.startedAt=new Date().toISOString();await fw(d);return b}
export async function finishBuild(id,status,result,error){if(pool){await pool.query('UPDATE builds SET status=$1,result=$2,error=$3,finished_at=NOW() WHERE build_id=$4',[status,result?JSON.stringify(result):null,error||null,id]);return}const d=await fr(),b=d.builds.find(x=>x.buildId===id);if(b){b.status=status;b.result=result||null;b.error=error||null;b.finishedAt=new Date().toISOString();await fw(d)}}
export async function resetStaleBuilds(){if(pool)await pool.query("UPDATE builds SET status='queued',started_at=NULL WHERE status='running'");else{const d=await fr();let c=0;for(const b of d.builds)if(b.status==='running'){b.status='queued';b.startedAt=null;c++}if(c)await fw(d)}}
